### ISSUE TITLE
Excuse me, have you experimented the DLG way in ResNet or any other net?

### ISSUE THREAD

**Issue by Harxis** [PatrickZH/Improved-Deep-Leakage-from-Gradients#2]
I have experimented the DLG way on LeNet and ResNet, I found DLG work on LeNet but fail on ResNet.I have followed the paper removing stride and replace activation function ReLu as Sigmoid.I saw you make a improvement on DLG way, so I think you might have done any experiment on ResNet.If you have done any experiment in ResNet, could you show me the code?

**Comment by PatrickZH** [comment]
I tried ResNet, but failed as well. I did similar experiments as you described. I think ResNet is too deep for realizing DLG.

**Comment by Harxis** [comment]
thank you
